# Generated by Django 3.2.8 on 2021-10-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conner',
            fields=[
                ('id', models.BigAutoField(help_text='Conner ID', primary_key=True, serialize=False)),
                ('frame_img', models.TextField(blank=True, help_text='Conner Representative Image', null=True)),
                ('video_id', models.IntegerField(help_text='Video_id')),
                ('conner_name', models.CharField(help_text='Conner Name', max_length=50)),
                ('conner_start', models.IntegerField(help_text='Conner Start')),
                ('conner_end', models.IntegerField(help_text='Conner End')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(help_text='Video ID', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Video Title', max_length=50)),
                ('path', models.CharField(help_text='Video Path', max_length=200)),
                ('conner', models.CharField(default='N', help_text='Conner Existence', max_length=5)),
            ],
        ),
    ]
